version: '3'
services:
        web:
                image: medipulse
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8115:8115"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
